LIB_SRC = 			\
	../src/net/Acceptor.cpp		\
	../src/net/Buffer.cpp		\
	../src/net/Channel.cpp		\
	../src/net/Connector.cpp		\
	../src/net/EPoller.cpp	 	\
	../src/net/EventLoop.cpp		\
	../src/net/EventLoopThread.cpp	\
	../src/net/EventLoopThreadPool.cpp	\
	../src/net/InetAddress.cpp		\
	../src/net/Poller.cpp		\
	../src/net/Socket.cpp		\
	../src/net/SocketsOps.cpp		\
	../src/net/TcpClient.cpp		\
	../src/net/TcpConnection.cpp	\
	../src/net/TcpServer.cpp		\
	../src/net/Timer.cpp		\
	../src/net/TimerQueue.cpp

BINARIES = test1 test2 test3 test4 test5 test6 test7 test8 test8_2 test9 test10 \
	   test11 test12 test13 test14

all: $(BINARIES)

include ./reactor_lib.mk

test1: ./test1.cc
test2: ./test2.cc
test3: ./test3.cc
test4: ./test4.cc
test5: ./test5.cc
test6: ./test6.cc
test7: ./test7.cc
test8: ./test8.cc
test8_2: ./test8.cc
test9: ./test9.cc
test10: ./test10.cc
test11: ./test11.cc
test12: ./test12.cc
test13: ./test13.cc
test14: ./test14.cc
